#!/bin/bash
# GitHub 推送脚本

echo "========================================="
echo "推送代码到 GitHub"
echo "========================================="
echo ""
echo "仓库地址: https://github.com/WoodConner/cve_livepatch_agent.git"
echo ""
echo "请按照以下步骤操作："
echo ""
echo "方法 1: 使用 Personal Access Token (推荐)"
echo "----------------------------------------"
echo "1. 访问 https://github.com/settings/tokens"
echo "2. 点击 'Generate new token (classic)'"
echo "3. 选择权限: repo (完整权限)"
echo "4. 生成并复制 token"
echo "5. 运行以下命令："
echo ""
echo "   cd /home/wood/cve_livepatch_agent"
echo "   git push -u origin main"
echo ""
echo "   当提示输入用户名时，输入: WoodConner"
echo "   当提示输入密码时，粘贴你的 Personal Access Token"
echo ""
echo ""
echo "方法 2: 使用 SSH (更安全)"
echo "----------------------------------------"
echo "1. 生成 SSH 密钥（如果还没有）："
echo "   ssh-keygen -t ed25519 -C 'your_email@example.com'"
echo ""
echo "2. 复制公钥："
echo "   cat ~/.ssh/id_ed25519.pub"
echo ""
echo "3. 添加到 GitHub:"
echo "   访问 https://github.com/settings/keys"
echo "   点击 'New SSH key' 并粘贴公钥"
echo ""
echo "4. 修改远程仓库 URL："
echo "   cd /home/wood/cve_livepatch_agent"
echo "   git remote set-url origin git@github.com:WoodConner/cve_livepatch_agent.git"
echo "   git push -u origin main"
echo ""
echo "========================================="
